import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import AceEditor from "react-ace";

const Converter: NextPage = () => {
  const [html, setHtml] = useState("Krishna");
  const [mjml, setmjml] = useState(`<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>
          Hello World!
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
  </mjml>`);

  const [context, setContext] = useState("{}");

  const getData = async () => {
    const rawResponse = await fetch("api/convert-mjml", {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ mjml: mjml, context: context }),
    });
    const data = await rawResponse.json();
    setHtml(data.html);
  };
  useEffect(() => {
    getData();
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>mjml converter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.flexrow}>
        <div className={styles.flexcol}>
          <textarea
            value={context}
            onChange={(e) => setContext(e.target.value)}
          ></textarea>
          <textarea
            value={mjml}
            onChange={(e) => setmjml(e.target.value)}
          ></textarea>
        </div>
        <div>
          <div dangerouslySetInnerHTML={{ __html: html }}></div>
        </div>
      </main>
    </div>
  );
};

export default Converter;
