import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [html, setHtml] = useState("");
  const [mjml, setmjml] = useState(`<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>
          Hello World!
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
  </mjml>`);

  const [context, setContext] = useState("{}");

  const getData = async () => {
    const rawResponse = await fetch("api/convert-mjml", {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ mjml: mjml, context: context }),
    });
    const data = await rawResponse.json();
    setHtml(data.html);
  };
  useEffect(() => {
    getData();
  });
  return (
    <div>
      <Head>
        <title>mjml converter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-2 gap-2 h-screen">
        <div className="grid grid-rows-2 border-2">
          <textarea
            className="border p-2 overflow-scroll"
            value={mjml}
            onChange={(e) => setmjml(e.target.value)}
          />
          <textarea
            className="border p-2 overflow-scroll"
            value={context}
            onChange={(e) => setContext(e.target.value)}
          />
        </div>
        <div className="border-2">
          <div dangerouslySetInnerHTML={{ __html: html }}></div>
        </div>
      </main>
    </div>
  );
};

export default Home;
